# Generated by Django 4.1.6 on 2023-09-06 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, unique=True)),
                ('number', models.IntegerField(blank=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=100, unique=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'single'), ('married', 'married'), ('widow', 'widow'), ('widower', 'widower')], max_length=100, unique=True)),
                ('tribe', models.CharField(blank=True, max_length=50, unique=True)),
                ('occupation', models.CharField(blank=True, max_length=50, unique=True)),
                ('societies', models.CharField(blank=True, max_length=100, unique=True)),
                ('dob', models.DateField(blank=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
