# Generated by Django 4.1.6 on 2023-09-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='number',
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
    ]
