# Generated by Django 4.1.6 on 2023-09-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profilemodel_address_alter_profilemodel_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='pics/'),
        ),
    ]
