# Generated by Django 4.1.6 on 2023-09-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(unique=True)),
                ('announcement', models.TextField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MassBookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('number', models.IntegerField(unique=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('thanksgiving', models.BooleanField(unique=True)),
                ('intention', models.TextField(max_length=1000, unique=True)),
            ],
        ),
    ]
