# Generated by Django 4.1.6 on 2023-09-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massbookingmodel',
            name='number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
