# Generated by Django 4.1.6 on 2023-09-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_announcementmodel_announcement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massbookingmodel',
            name='thanksgiving',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20),
        ),
    ]
