# Generated by Django 4.1.6 on 2023-09-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_massbookingmodel_thanksgiving'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=11)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
